//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp4tag.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mp4tag.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp4tag.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string autoUpdate {
            get {
                return ResourceManager.GetString("autoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.t-mueller.net/downloads/Mp4tag/RELEASENOTES.rtf.
        /// </summary>
        internal static string autoUpdateReleaseNotesUrl {
            get {
                return ResourceManager.GetString("autoUpdateReleaseNotesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.t-mueller.net/downloads/Mp4tag/SetupMp4tag.exe.
        /// </summary>
        internal static string autoUpdateSetupUrl {
            get {
                return ResourceManager.GetString("autoUpdateSetupUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.t-mueller.net/downloads/Mp4tag/VERSION.
        /// </summary>
        internal static string autoUpdateVersionUrl {
            get {
                return ResourceManager.GetString("autoUpdateVersionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string defaultLanguage {
            get {
                return ResourceManager.GetString("defaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR,G,PG,PG-13,R,NC-17,Unrated.
        /// </summary>
        internal static string defaultMovieRating {
            get {
                return ResourceManager.GetString("defaultMovieRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpaa.
        /// </summary>
        internal static string defaultMovieSource {
            get {
                return ResourceManager.GetString("defaultMovieSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV-Y,TV-Y7,TV-G,TV-PG,TV-14,TV-MA,Unrated.
        /// </summary>
        internal static string defaultTvRating {
            get {
                return ResourceManager.GetString("defaultTvRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us-tv.
        /// </summary>
        internal static string defaultTvSource {
            get {
                return ResourceManager.GetString("defaultTvSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string languageVersion {
            get {
                return ResourceManager.GetString("languageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Mp4tag {
            get {
                object obj = ResourceManager.GetObject("Mp4tag", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noImage {
            get {
                object obj = ResourceManager.GetObject("noImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
